const BASEURL = 'http://localhost:9093';

const STOREKEY = 'LEX_REACT_ADMIN';

const LOGIN_SIGN_TIMEOUT = 'LOGIN_SIGN_TIMEOUT';
const LOGIN_SIGN_OK = 'OK';
const LOGIN_SIGN_ERROR = 'ERROR';

const AUTHORITYOPEN = true;

export {
  BASEURL,
  STOREKEY,
  LOGIN_SIGN_TIMEOUT,
  LOGIN_SIGN_OK,
  LOGIN_SIGN_ERROR,
  AUTHORITYOPEN
};
