export const USER_LOGIN_REQUEST = 'COMMON/USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'COMMON/USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'COMMON/USER_LOGIN_FAILURE';

export const SETTING_UPDATE = 'COMMON/SETTING_UPDATE';
export const GLOBAL_UPDATE = 'COMMON/GLOBAL_UPDATE';
